#ifndef _UAPI_LINUX_MODULE_H
#define _UAPI_LINUX_MODULE_H

/* Flags for sys_finit_module: */
#define MODULE_INIT_IGNORE_MODVERSIONS	1
#define MODULE_INIT_IGNORE_VERMAGIC	2
#define MODULE_INIT_LOCKDOWN		4

#endif /* _UAPI_LINUX_MODULE_H */
